package ca.team50.Tiles;

public enum Tile {
    LAND,OCEAN,LAGOON,BEACH,LAKE,
    TUNDRA,TAIGA,ICECAP,BOREAL,COLDDESERT,
    OASIS,GRASSLAND,SAND,BADLANDS,SAGEBRUSH,
    RAINFOREST,SAVANNAH,MANGROVE,CLOUDFOREST,SWAMP,

    TOWN,SMALLCITY,REGIOPOLIS,METROPOLIS

}
